### PR TITLE
Feature/layouter bugfixes - part1: caching bug in Brick

### LINKED ISSUE #628: caching bug in brick neighbors
bricks sometimes have invalid neighbor bricks in their caches
e.g. the cache does not get cleared at all necessary times
discovered in #615

### PR DESCRIPTION
**Pull request by johannesdeselaers**
closes #628

also includes some refactoring

### CODE REVIEW

File: src/plugins/newBrickator/pipeline/Brick.coffee [hunk 1]
```diff
@@ -146,14 +146,17 @@ class Brick
 	# Returns a set of all bricks that are next to this brick
 	# in the given direction
 	getNeighbors: (direction) =>
+		###
+			TODO
```
Comment (Steditor) [inline src/plugins/newBrickator/pipeline/Brick.coffee]: Please create a issue for this with a milestone with due date.

File: src/plugins/newBrickator/pipeline/Grid.coffee [hunk 2]
```diff
@@ -1,3 +1,5 @@
+log = require 'loglevel'
```
Comment (Steditor) [inline src/plugins/newBrickator/pipeline/Grid.coffee]: Where do you use log in this file?

File: src/plugins/newBrickator/pipeline/Grid.coffee [hunk 3]
```diff
@@ -277,6 +279,12 @@ module.exports = class Grid
 
 		return bricks
 
+	getAllVoxels: =>
```
Comment (Steditor) [inline src/plugins/newBrickator/pipeline/Grid.coffee]: In the long run we should try to get rid of https://github.com/brickify/brickify/blob/develop/src/plugins/nodeVisualizer/VoxelSelector.coffee#L18

File: src/plugins/newBrickator/pipeline/Layout/BrickLayouter.coffee [hunk 4]
```diff
@@ -146,65 +146,22 @@ class BrickLayouter extends Layouter
...
-				return secondLayerBricks
-
-		# No mergeable neighbors
-		return null
-
-
-	_sameSizeAsBrick: (brick, layerBricks) =>
-		return false if layerBricks.size is 0
+		secondLayerBricks = brick.getNeighbors(Brick.direction.Zp)
+		return null unless secondLayerBricks.size == 1
```
Comment (Steditor) [inline src/plugins/newBrickator/pipeline/Layout/BrickLayouter.coffee]: `is` instead of `==` :wink:

File: src/plugins/newBrickator/pipeline/Grid.coffee (hunk 2 above)
Comment (johannesdeselaers) [inline src/plugins/newBrickator/pipeline/Grid.coffee]: not currently, but every now and then for debugging
i could take it out, but i feel that it also doesn't hurt, if it stays in

**Comment by Steditor** [comment]
:boat:
